Repository Nexters/Bottles_iOS, pull requests merged in 2024-09, with the labels that each got.

#227 [Feature/#207] 사진 공개 프로필 이미지 비율 수정
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PhotoSharePingPongView.swift
Labels: 🐞 Bug

#230 [feature#221] 버튼 throttling 처리
  Projects/Shared/DesignSystem/Sources/Modifiers/AsThrottleButtonModifier.swift
Labels: 💎 Feature

#234 [fix#223] 이미지 선택 시 버튼 활성화되지 않는 버그
  Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadView.swift
Labels: 🐞 Bug

#238 [Docs#237] README 작성
  README.md
Labels: ⚙️ Setting

#246 Feature/#231 커스텀 alert 구현
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon/icon_warning.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon/icon_warning.imageset/icon_warning.svg
  Projects/Shared/DesignSystem/Sources/Components/Alert/BottleAlert.swift
  Projects/Shared/DesignSystem/Sources/Components/Alert/BottleAlertView.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButton.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButtonStyle.swift
  Projects/Shared/DesignSystem/Sources/Image/BottleImageSystem+Icon.swift
Labels: 💎 Feature

#229 [Feature/#224] lists design system
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/ListTest/ListTestView.swift
  Projects/Shared/DesignSystem/Sources/Components/List/ArrowListView.swift
  Projects/Shared/DesignSystem/Sources/Components/List/ButtonListView.swift
  Projects/Shared/DesignSystem/Sources/Components/List/ListContainerView.swift
  Projects/Shared/DesignSystem/Sources/Components/List/TextListView.swift
  Projects/Shared/DesignSystem/Sources/Components/List/ToggleListView.swift
  Projects/Shared/DesignSystem/Sources/Components/Toggle/BottleToggle.swift
Labels: 💎 Feature

#249 [Feature/#225] 마이페이지 리뉴얼 작업
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
Labels: 💎 Feature

#253 [Feature/#252] 마이페이지 알림설정 구현
  Projects/Domain/User/Interface/Sources/API/UserAPI.swift
  Projects/Domain/User/Interface/Sources/DTO/Request/AlertStateRequestDTO.swift
  Projects/Domain/User/Interface/Sources/DTO/Response/AlertStateReponseDTO.swift
  Projects/Domain/User/Interface/Sources/Entity/AlertState.swift
  Projects/Domain/User/Interface/Sources/Entity/AlertType.swift
  Projects/Domain/User/Interface/Sources/UserClient.swift
  Projects/Domain/User/Sources/UserClient.swift
  Projects/Feature/MyPage/Interface/Sources/AlertSetting/AlertSettingFeature.swift
  Projects/Feature/MyPage/Interface/Sources/AlertSetting/AlertSettingFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/AlertSetting/AlertSettingView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRootFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRootFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRootView.swift
  Projects/Feature/Sources/TabView/MainTabView.swift
  Projects/Feature/Sources/TabView/MainTabViewFeature.swift
Labels: 💎 Feature

#255 [Feature/#254] 마이페이지 계정 관리 구현
  Projects/Domain/Profile/Interface/Sources/API/ProfileAPI.swift
  Projects/Domain/Profile/Interface/Sources/DTO/Request/MatchingActivateRequestDTO.swift
  Projects/Domain/Profile/Interface/Sources/DTO/Response/ProfileResponseDTO.swift
  Projects/Domain/Profile/Interface/Sources/ProfileClient.swift
  Projects/Domain/Profile/Sources/ProfileClient.swift
  Projects/Feature/MyPage/Interface/Sources/AccountSetting/AccountSettingFeature.swift
  Projects/Feature/MyPage/Interface/Sources/AccountSetting/AccountSettingFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/AccountSetting/AccountSettingView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRootFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRootFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRootView.swift
Labels: 💎 Feature

#256 [Feature/#251] 연락처 차단 기능 구현
  Projects/Core/Network/Project.swift
  Projects/Domain/User/Interface/Sources/API/UserAPI.swift
  Projects/Domain/User/Interface/Sources/DTO/Request/BlockContactRequestDTO.swift
  Projects/Domain/User/Interface/Sources/UserClient.swift
  Projects/Domain/User/Interface/Sources/UserError.swift
  Projects/Domain/User/Sources/UserClient.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Shared/DesignSystemThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: 💎 Feature

#260 [Feature/#259] 마이페이지 1:1 문의 기능 구현
  Projects/Core/URLHandler/Interface/Sources/BottleURLType.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: 💎 Feature

#258 [Feature/#257] 마이페이지 앱 버전 업데이트 기능 구현
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Projects/Core/URLHandler/Interface/Sources/BottleURLType.swift
  Projects/Domain/Application/Interface/Sources/ApplicationClient.swift
  Projects/Domain/Application/Project.swift
  Projects/Domain/Application/Sources/ApplicationClient.swift
  Projects/Domain/Application/Testing/Sources/ApplicationTesting.swift
  Projects/Domain/Application/Tests/Sources/ApplicationTest.swift
  Projects/Domain/User/Sources/UserClient.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Shared/DesignSystem/Sources/Components/List/ButtonListView.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: 💎 Feature

#270 [feature/#264] 마이페이지 프로필 수정 웹뷰 연결
  Projects/Feature/BaseWebView/Interface/Sources/BaseWebView.swift
  Projects/Feature/BaseWebView/Interface/Sources/BaseWebViewType.swift
  Projects/Feature/MyPage/Example/Sources/AppView.swift
  Projects/Feature/MyPage/Interface/Sources/EditProfile/EditProfileFeature.swift
  Projects/Feature/MyPage/Interface/Sources/EditProfile/EditProfileFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/EditProfile/ProfileEditView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRootFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRootFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRootView.swift
  Projects/Feature/MyPage/Project.swift
Labels: 💎 Feature

#265 [Feature/#263] 연락처 접근 권한 허용안함 시 설정 이동
  Projects/Core/URLHandler/Interface/Sources/BottleURLType.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
Labels: 💎 Feature

#267 [Feature/#266] 마이페이지 진입 시 연락처 차단 개수 동기화
  Projects/Domain/Profile/Interface/Sources/DTO/Response/ProfileResponseDTO.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
Labels: 💎 Feature

#269 [Feature/#268] 연락처 차단 완료 시 Toast 띄우기
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
Labels: 💎 Feature

#279 [Feature/#277] 웹뷰 os type, 버전 파라미터 추가
  Projects/Feature/BaseWebView/Interface/Sources/BaseWebViewType.swift
Labels: 💎 Feature

#284 [Feature/#278] 웹뷰 상단 safe area 무시하도록 수정
  Projects/Feature/BottleArrival/Interface/Sources/BottleArrivalView.swift
  Projects/Feature/GeneralSignUp/Interface/Sources/GeneralSignUpView.swift
  Projects/Feature/Login/Interface/Sources/GeneralLogIn/GeneralLogInView.swift
  Projects/Feature/MyPage/Interface/Sources/EditProfile/ProfileEditView.swift
  Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingView.swift
Labels: 💎 Feature

#281 [Fix/#280] 로그인화면 백그라운드 이미지 비율 수정
  Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
Labels: 🐞 Bug

#283 [Fix/#282] 로그인 화면 로그인 버튼 vstack 하단 마진 수정
  Projects/Feature/Login/Interface/Sources/Login/AppleLoginView.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
Labels: 🐞 Bug

#272 [Feature/#232] 커스텀 alert 적용
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift
  Projects/Feature/Report/Interface/Sources/ReportUserFeature.swift
  Projects/Feature/Report/Interface/Sources/ReportUserFeatureInterface.swift
  Projects/Feature/Report/Interface/Sources/ReportUserView.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachView.swift
  Projects/Feature/Sources/SplashView/SplashView.swift
Labels: 💎 Feature

#274 [Feature/#273] 탈퇴하기 alert message 수정
  Projects/Feature/MyPage/Interface/Sources/AccountSetting/AccountSettingFeature.swift
Labels: 💎 Feature
