Repository Nexters/Bottles_iOS, pull requests merged in 2024-11, with the labels that each got.

#338 [Feature/#331] 코치 마크 구현
  Projects/Domain/User/Interface/Sources/UserClient.swift
  Projects/Domain/User/Sources/UserClient.swift
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootView.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachView.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeachCoachMark/SandBeachCoachMarkFeature.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeachCoachMark/SandBeachCoachMarkFeatureInterface.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeachCoachMark/SandBeachCoachMarkView.swift
  Projects/Feature/TabBar/Interface/Sources/TabBarModifier.swift
  Projects/Shared/DesignSystem/Sources/Components/Popup/PopupType.swift
  Projects/Shared/DesignSystem/Sources/Components/Popup/PopupView.swift
  Projects/Shared/DesignSystem/Sources/Font/BottleFontSystem+WantedSans.swift
Labels: 💎 Feature

#336 [Feature/#335] 문답 화면 텍스트필드 버그 수정
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift
  Projects/Shared/DesignSystem/Sources/Components/TextField/LinesTextField/LinesTextField.swift
Labels: 🐞 Bug

#337 [Feature/#329] 사진 3개 등록 대응
  Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottlePingPongResponseDTO.swift
  Projects/Domain/Bottle/Interface/Sources/Entity/BottlePingPong.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PhotoSharePingPongView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift
Labels: 💎 Feature

#344 [Feature/#343] 프로필 수정 완료 후 업데이트 처리
  Projects/Core/WebView/Interface/Sources/BottleWebViewAction.swift
  Projects/Feature/MyPage/Interface/Sources/EditProfile/EditProfileFeature.swift
  Projects/Feature/MyPage/Interface/Sources/EditProfile/EditProfileFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/EditProfile/ProfileEditView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRootFeatureInterface.swift
Labels: 💎 Feature

#347 [Feature/#346] 웹뷰 safearea top ingore 처리
  Projects/Feature/BottleArrival/Interface/Sources/BottleArrivalDetail/BottleArrivalDetailView.swift
  Projects/Feature/GoodFeeling/Interface/Sources/SentBottleDetail/SentBottleDetailView.swift
Labels: 💎 Feature

#348 [Feature/#328] 자기 소개 웹뷰 연결
  Projects/Core/WebView/Interface/Sources/BottleWebViewAction.swift
  Projects/Feature/BaseWebView/Interface/Sources/BaseWebViewType.swift
  Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupFeature.swift
  Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupView.swift
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift
Labels: 💎 Feature

#350 [Feature/#349] 보틀 보관함 디자인 qa 반영
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/QuestionPingPongView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/Stop/StopCardView.swift
Labels: 🛠️ Refactor

#342 [Feature/#339] 앱 알림 설정 유무 등록 API 연결
  Projects/Core/Network/Sources/MoyaPulgins/MoyaLoggerPlugin.swift
  Projects/Domain/User/Interface/Sources/API/UserAPI.swift
  Projects/Domain/User/Interface/Sources/DTO/Request/UpdatePushNotificationAllowStatusRequestDTO.swift
  Projects/Domain/User/Interface/Sources/NeedUpdatePushNotificationAllowStatusRemotelyType.swift
  Projects/Domain/User/Interface/Sources/UserClient.swift
  Projects/Domain/User/Sources/UserClient.swift
  Projects/Feature/MyPage/Interface/Sources/AlertSetting/AlertSettingFeature.swift
  Projects/Feature/Sources/App/AppDelegateFeature.swift
  Projects/Feature/Sources/SplashView/SplashFeature.swift
  Projects/Shared/Util/Interface/Sources/UtilInterface.swift
Labels: 💎 Feature

#354 [Feature/#353] 모래사장 화면 자기소개 작성 및 보틀 보여주기 로직 원복
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift
Labels: 💎 Feature

#356 [Feature/#355] 웹뷰에서 카메라 접근 시 핸들링
  Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: 💎 Feature

#358 [Feature/#357] 로딩 인디케이터 변경된 디자인 반영
  Projects/Shared/DesignSystem/Resources/Lotties.xcassets/Bottle_loading_ellipse.dataset/Bottle_loading_ellipse.json
  Projects/Shared/DesignSystem/Resources/Lotties.xcassets/Bottle_loading_ellipse.dataset/Contents.json
  Projects/Shared/DesignSystem/Resources/Lotties.xcassets/ProgressIndicator.dataset/ProgressIndicator.lottie
  Projects/Shared/DesignSystem/Sources/ProgressIndicator/LoadingIndicator.swift
Labels: 💎 Feature

#359 [Feature/#318] 도착한 보틀 리스트, 도착한 보틀 상세 화면 로딩 인디케이터 적용
  Projects/Feature/GoodFeeling/Interface/Sources/GoodFeeling/GoodFeelingFeature.swift
  Projects/Feature/GoodFeeling/Interface/Sources/GoodFeeling/GoodFeelingFeatureInterface.swift
  Projects/Feature/GoodFeeling/Interface/Sources/GoodFeeling/GoodFeelingView.swift
  Projects/Feature/GoodFeeling/Interface/Sources/SentBottleDetail/SentBottleDetailFeature.swift
  Projects/Feature/GoodFeeling/Interface/Sources/SentBottleDetail/SentBottleDetailFeatureInterface.swift
  Projects/Feature/GoodFeeling/Interface/Sources/SentBottleDetail/SentBottleDetailView.swift
Labels: 💎 Feature

#361 [Feature#360]: 모래사장 화면 자기소개 작성 및 보틀 보여주기 로직 수정
  Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupFeature.swift
  Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupView.swift
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift
  Projects/Feature/Sources/TabView/MainTabViewFeature.swift
Labels: 🐞 Bug
