Repository Nexters/Bottles_iOS, pull requests merged in 2024-10, with the labels that each got.

#304 [Setting/#303] assertion error 슬랙 로깅 연결
  Projects/Core/Logger/Interface/Sources/Log.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: ⚙️ Setting

#309 [Fix/#308] onboarding 4 디자인 qa 반영
  Projects/Feature/Guide/Interface/Sources/StartGuide/StartGuideView.swift
Labels: 🐞 Bug

#311 [refactor/#310] 마이페이지 중복된 setTabBar 모디파이어 제거
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPageRootView.swift
Labels: 🛠️ Refactor

#312 [Refactor/#296] 웹뷰 프로필 생성 변경된 URL 적용
  Projects/Feature/BaseWebView/Interface/Sources/BaseWebViewType.swift
Labels: 🛠️ Refactor

#315 [Fix/#314] 보틀 보관함 하단에 탭 높이만큼 패딩값 추가 필요
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift
Labels: 🐞 Bug

#320 [Refactor/#319] 프로필 이미지 블러 처리 로직 제거
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift
  Projects/Feature/Report/Interface/Sources/ReportUserView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/UserProfileTest/UserProfileTestView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/UserProfile/UserProfileView.swift
  Projects/Shared/DesignSystem/Sources/Components/ListItem/BottleStorageItem.swift
Labels: 🛠️ Refactor

#292 [Feature/#290] 문답화면 리스트 디자인시스템 구현
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/BottleStorageList.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/PingPong/PingPongUserView.swift
Labels: 💎 Feature

#297 [Feature/#294] 문답화면 segmented control 디자인 수정
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/SegmentControlButton/SegmentControlButton.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/SegmentControlButton/SegmentControlButtonStyle.swift
Labels: 💎 Feature

#325 [Feature/#324] 문답 화면 새로운 디자인 적용
  Projects/Domain/Bottle/Interface/Sources/API/BottleAPI.swift
  Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottleStorageListResponseDTO.swift
  Projects/Domain/Bottle/Interface/Sources/Entity/BottleStorageList.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachView.swift
  Projects/Feature/Sources/TabView/MainTabViewFeature.swift
Labels: 💎 Feature
