Repository Nexters/Bottles_iOS, pull requests merged in 2024-08, with the labels that each got.

#57 [Feature/#55] ClipList DesignSystem 구현
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/ClipListTest/ClipListContainerViewTest.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/ClipListTest/ClipListViewTest.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/ChipListLayout.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/ClipItem.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/ClipListContainerView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/ClipListView.swift
Labels: 💎 Feature

#59 [Feature/#58] 프로필 만들기 Domain 구현
  Projects/Domain/Auth/Interface/Sources/LoginManager/LoginManager.swift
  Projects/Domain/Auth/Sources/LoginManager/LoginManager.swift
  Projects/Domain/Profile/Interface/Sources/API/ProfileAPI.swift
  Projects/Domain/Profile/Interface/Sources/DTO/Request/RegisterIntroductionRequestDTO.swift
  Projects/Domain/Profile/Interface/Sources/DTO/Response/IntroductionExistResponseDTO.swift
  Projects/Domain/Profile/Interface/Sources/DTO/Response/ProfileResponseDTO.swift
  Projects/Domain/Profile/Interface/Sources/Entity/UserInterest.swift
  Projects/Domain/Profile/Interface/Sources/Entity/UserProfile.swift
  Projects/Domain/Profile/Interface/Sources/Entity/UserRegion.swift
  Projects/Domain/Profile/Interface/Sources/ProfileClient.swift
  Projects/Domain/Profile/Sources/ProfileClient.swift
Labels: 💎 Feature

#60 [Feature/#52] Login Feature 구현
  Projects/Core/Network/Interface/Sources/API/BaseTargetType.swift
  Projects/Core/Network/Interface/Sources/NetworkManager/NetworkManagable.swift
  Projects/Core/Network/Interface/Sources/Provider/Providable.swift
  Projects/Core/Network/Sources/Interceptor/Refresh/RefreshAPI.swift
  Projects/Core/Network/Sources/Interceptor/Refresh/RefreshResponseDTO.swift
  Projects/Core/Network/Sources/Interceptor/TokenInterceptor.swift
  Projects/Core/Network/Sources/NetworkManager/NetworkManager.swift
  Projects/Core/Network/Sources/Provider/Provider.swift
  Projects/Domain/Auth/Interface/Sources/DTO/Response/SignInResponseDTO.swift
  Projects/Feature/Login/Example/Sources/AppView.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeatureInterface.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
  Projects/Feature/Login/Sources/Login/LoginFeature.swift
  Projects/Feature/Sources/App/AppFeature.swift
Labels: 💎 Feature

#66 [Feature/#56] ETC DesignSystem 일부 구현
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/ClipListTest/ClipListContainerViewTest.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/ClipListTest/ClipListViewTest.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/ETCTest/PageIndicatorTestView.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_arrow_left.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_arrow_left.imageset/icon_arrow_left.svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_delete.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_delete.imageset/icon_delete.svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_down.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_down.imageset/icon_down.svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_plus.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_plus.imageset/icon_plus.svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_right.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_right.imageset/icon_right.svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_share.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_share.imageset/icon_share.svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_siren.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_siren.imageset/icon_siren.svg
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_up.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_up.imageset/icon_up.svg
  Projects/Shared/DesignSystem/Sources/Color/BottleColorSystem+Neutral.swift
  Projects/Shared/DesignSystem/Sources/Color/BottleColorSystem+Primary.swift
  Projects/Shared/DesignSystem/Sources/Color/BottleColorSystem+Sub.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/OutlinedButton/OutlinedStyleButton.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/ChipListLayout.swift
  Projects/Shared/DesignSystem/Sources/Components/ETC/ImagePickerButton.swift
  Projects/Shared/DesignSystem/Sources/Components/ETC/PageIndicatorView.swift
  Projects/Shared/DesignSystem/Sources/Components/ETC/TitleView.swift
  Projects/Shared/DesignSystem/Sources/Components/ImageView/BottleImageView.swift
  Projects/Shared/DesignSystem/Sources/Components/ImageView/ImageViewType.swift
  Projects/Shared/DesignSystem/Sources/Components/ImageView/LocalImageView.swift
  Projects/Shared/DesignSystem/Sources/Components/Popup/TriangleShape.swift
  Projects/Shared/DesignSystem/Sources/Components/Popup/TriangleView.swift
  Projects/Shared/DesignSystem/Sources/Extension/Text+Color.swift
  Projects/Shared/DesignSystem/Sources/Image/BottleImageSystem+Icon.swift
  Projects/Shared/DesignSystem/Sources/Image/Image+Extensions.swift
  Projects/Shared/DesignSystem/Sources/Image/Imageable.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: 💎 Feature

#65 Setting/#64 App Store Connect 등록 준비
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Project+Environment.swift
Labels: 💎 Feature

#71 Fix/#70 App View WithPerceptionTracking 처리
  Projects/Feature/Sources/App/AppView.swift
  Projects/Feature/Sources/TabView/MainTabView.swift
Labels: 🐞 Bug

#62 Feature/#53 onboardingfeature 구현
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Projects/Core/Util/Interface/Sources/Source.swift
  Projects/Core/Util/Interface/Sources/UtilInterface.swift
  Projects/Core/WebView/Interface/Sources/WebViewMessageHandler.swift
  Projects/Core/WebView/Interface/Sources/WebViewURL.swift
  Projects/Core/WebView/Project.swift
  Projects/Core/WebView/Sources/Source.swift
  Projects/Core/WebView/Testing/Sources/WebViewTesting.swift
  Projects/Core/WebView/Tests/Sources/WebViewTest.swift
  Projects/Feature/Onboarding/Example/Sources/AppView.swift
  Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingFeatureInterface.swift
  Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingView.swift
  Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingWebView.swift
  Projects/Feature/Onboarding/Project.swift
  Projects/Feature/Onboarding/Sources/Onboarding/OnboardingFeature.swift
  Projects/Feature/Onboarding/Testing/Sources/OnboardingTesting.swift
  Projects/Feature/Onboarding/Tests/Sources/OnboardingTest.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: 💎 Feature

#69 Feature/#61 webview 초안 구현
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Projects/App/Sources/AppRoot.swift
  Projects/Core/Logger/Interface/Sources/Log.swift
  Projects/Core/Toast/Interface/Sources/ToastClient.swift
  Projects/Core/Toast/Project.swift
  Projects/Core/Toast/Sources/Source.swift
  Projects/Core/Toast/Testing/Sources/ToastTesting.swift
  Projects/Core/Toast/Tests/Sources/ToastTest.swift
  Projects/Core/WebView/Interface/Sources/BottleWebViewAction.swift
  Projects/Core/WebView/Interface/Sources/BottleWebViewType.swift
  Projects/Core/WebView/Project.swift
  Projects/Domain/WebView/Interface/Sources/WebViewHandleClientInterface.swift
  Projects/Domain/WebView/Project.swift
  Projects/Domain/WebView/Sources/WebViewClient.swift
  Projects/Domain/WebView/Testing/Sources/WebViewTesting.swift
  Projects/Domain/WebView/Tests/Sources/WebViewTest.swift
  Projects/Feature/BaseWebView/Example/Sources/AppView.swift
  Projects/Feature/BaseWebView/Interface/Sources/BaseWebView.swift
  Projects/Feature/BaseWebView/Project.swift
  Projects/Feature/BaseWebView/Sources/Source.swift
  Projects/Feature/BaseWebView/Testing/Sources/BottleWebViewTesting.swift
  Projects/Feature/BaseWebView/Tests/Sources/BottleWebViewTest.swift
  Projects/Feature/GeneralSignUp/Example/Sources/AppView.swift
  Projects/Feature/GeneralSignUp/Interface/Sources/GeneralSignUpFeatureInterface.swift
  Projects/Feature/GeneralSignUp/Interface/Sources/GeneralSignUpView.swift
  Projects/Feature/GeneralSignUp/Project.swift
  Projects/Feature/GeneralSignUp/Sources/GeneralSignUpFeature.swift
  Projects/Feature/GeneralSignUp/Testing/Sources/GeneralSignUpTesting.swift
  Projects/Feature/GeneralSignUp/Tests/Sources/GeneralSignUpTest.swift
  Projects/Feature/Login/Interface/Sources/GeneralLogIn/GeneralLogInFeatureInterface.swift
  Projects/Feature/Login/Interface/Sources/GeneralLogIn/GeneralLogInView.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeatureInterface.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
  Projects/Feature/Login/Project.swift
  Projects/Feature/Login/Sources/Login/LoginFeature.swift
  Projects/Feature/Login/Sources/Source.swift
  Projects/Feature/MyPage/Example/Sources/AppView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Feature/MyPage/Project.swift
  Projects/Feature/MyPage/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingFeatureInterface.swift
  Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingView.swift
  Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingWebView.swift
  Projects/Feature/Onboarding/Project.swift
  Projects/Feature/Onboarding/Sources/Onboarding/OnboardingFeature.swift
  Projects/Feature/Sources/App/AppFeature.swift
  Projects/Shared/DesignSystem/Example/Sources/AppView.swift
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/ToastTestView.swift
  Projects/Shared/DesignSystem/Sources/Components/Toast/PassthroughWindow.swift
  Projects/Shared/DesignSystem/Sources/Components/Toast/RootView.swift
  Projects/Shared/DesignSystem/Sources/Components/Toast/ToastGroupView.swift
  Projects/Shared/DesignSystem/Sources/Components/Toast/ToastItem.swift
  Projects/Shared/DesignSystem/Sources/Components/Toast/ToastItemView.swift
  Projects/Shared/DesignSystem/Sources/Components/Toast/ToastManager.swift
  graph.png
Labels: 💎 Feature

#77 [Feature/#75] 편지 카드 DesginSystem 구현
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/LetterCardTest/LetterCardTestView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/ClipList/ChipListLayout.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/ClipList/ClipItem.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/ClipList/ClipListContainerView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/ClipList/ClipListView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/Letter/LettetCardView.swift
Labels: 💎 Feature

#81 [Feature/#80] 대화 중단 Card DesignSystem 구현
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/StopCardTest/StopCardTestView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/Stop/StopCardView.swift
Labels: 💎 Feature

#83 [Feature/#76] 로딩 프로그레스 뷰 구현
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/TargetDependency+SPM.swift
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Project.swift
  Projects/Shared/DesignSystem/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/Shared/DesignSystem/Resources/Assets.xcassets/Contents.json
  Projects/Shared/DesignSystem/Resources/Lotties.xcassets/Contents.json
  Projects/Shared/DesignSystem/Resources/Lotties.xcassets/ProgressIndicator.dataset/Contents.json
  Projects/Shared/DesignSystem/Resources/Lotties.xcassets/ProgressIndicator.dataset/ProgressIndicator.lottie
  Projects/Shared/DesignSystem/Sources/ProgressIndicator/LoadingIndicator.swift
  Projects/Shared/DesignSystemThirdPartyLib/Project.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ResourceSynthesizers/Lottie.stencil
Labels: 💎 Feature

#84 [Feature/#74] 보틀 보관함 root view 구현
  Projects/Domain/Bottle/Interface/Sources/API/BottleAPI.swift
  Projects/Domain/Bottle/Interface/Sources/BottleClient.swift
  Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottleListResponseDTO.swift
  Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottleStorageListResponseDTO.swift
  Projects/Domain/Bottle/Interface/Sources/Entity/BottleStorageList.swift
  Projects/Domain/Bottle/Sources/BottleClient.swift
  Projects/Feature/BottleStorage/Example/Sources/AppView.swift
  Projects/Feature/BottleStorage/Example/Sources/Source.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift
  Projects/Feature/BottleStorage/Sources/BottleStorage/BottleStorageFeature.swift
  Projects/Feature/BottleStorage/Sources/Source.swift
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/BottleStorageList.swift
  Projects/Shared/DesignSystem/Sources/Components/ImageView/RemoteImageView.swift
  Projects/Shared/DesignSystem/Sources/Components/ListItem/BottleStorageItem.swift
Labels: 💎 Feature

#89 [Feature/#82] PingPong DesignSystem
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/PingPongTest/FinalSelectPingPongTestView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/PingPongTest/PhotoSharePingPongTestView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/PingPongTest/QuestionPingPongTestView.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/OutlinedButton/OutlinedStyleButton.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/PingPong/FinalSelectPingPongView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/PingPong/FinalSelectStateType.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/PingPong/PhotoSharePingPongView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/PingPong/PhotoShareStateType.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/PingPong/PingPongBubble.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/PingPong/PingPongContainerView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/PingPong/QuestionPingPongView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/PingPong/QuestionStateType.swift
  Projects/Shared/DesignSystem/Sources/Components/ImageView/LocalImageView.swift
  Projects/Shared/DesignSystem/Sources/Components/TextField/LinesTextField/LinesTextField.swift
  Projects/Shared/DesignSystem/Sources/Extension/View+Extensions.swift
  Projects/Shared/DesignSystem/Sources/Extension/View+RoundedCorner.swift
Labels: 💎 Feature

#86 [Faeture/#85] 프로필 웹뷰 이벤트 핸들링
  Projects/Core/WebView/Interface/Sources/BottleWebViewAction.swift
  Projects/Core/WebView/Interface/Sources/BottleWebViewType.swift
  Projects/Domain/Auth/Interface/Sources/DTO/Response/SignInResponseDTO.swift
  Projects/Feature/BaseWebView/Interface/Sources/BaseWebView.swift
  Projects/Feature/BaseWebView/Interface/Sources/BottleWebViewType.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeature.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeatureInterface.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
  Projects/Feature/Login/Project.swift
  Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingFeature.swift
  Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingFeatureInterface.swift
  Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingView.swift
  Projects/Feature/Onboarding/Sources/Source.swift
  Projects/Feature/Sources/App/AppFeature.swift
Labels: 💎 Feature

#96 [Feature/#87] 마이 페이지 웹뷰 이벤트 핸들링
  Projects/Core/WebView/Interface/Sources/BottleWebViewAction.swift
  Projects/Domain/Auth/Interface/Sources/API/AuthAPI.swift
  Projects/Domain/Auth/Interface/Sources/AuthClient.swift
  Projects/Domain/Auth/Sources/AuthClient.swift
  Projects/Feature/BaseWebView/Interface/Sources/BaseWebView.swift
  Projects/Feature/BaseWebView/Interface/Sources/BaseWebViewType.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Feature/MyPage/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Sources/Source.swift
  Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingView.swift
  Projects/Feature/Sources/App/AppFeature.swift
  Projects/Feature/Sources/TabView/MainTabViewFeature.swift
Labels: 💎 Feature

#98 [Feature/#92] 모래사장 화면 일러스트이미지 작업
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachView.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/UserStateType.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButton.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButtonStyle.swift
  Projects/Shared/DesignSystem/Sources/Components/Popup/PopupView.swift
  Projects/Shared/DesignSystem/Sources/Components/Popup/TriangleView.swift
  Projects/Shared/DesignSystem/Sources/Extension/View+Extensions.swift
  Projects/Shared/DesignSystem/Sources/Padding/BottlePaddingType.swift
  Projects/Shared/DesignSystem/Sources/Radius/BottleRadiusType.swift
Labels: 💎 Feature

#104 [feature/#102] 보틀 보관함 상세 탭뷰 구현
  Projects/Feature/BottleStorage/Example/Sources/AppView.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift
  Projects/Feature/SandBeach/Example/Sources/AppView.swift
  Projects/Shared/DesignSystem/Sources/Extension/PreferenceKey/CGSizePreferenceKey.swift
  Projects/Shared/DesignSystem/Sources/Extension/View+Extensions.swift
Labels: 💎 Feature

#113 [Feature#95] 모래사장 도착한 보틀 웹뷰 연결
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Projects/Domain/Bottle/Interface/Sources/BottleClient.swift
  Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottleListResponseDTO.swift
  Projects/Domain/Bottle/Sources/BottleClient.swift
  Projects/Feature/BaseWebView/Interface/Sources/BaseWebViewType.swift
  Projects/Feature/BottleArrival/Example/Sources/AppView.swift
  Projects/Feature/BottleArrival/Interface/Sources/BottleArrivalFeature.swift
  Projects/Feature/BottleArrival/Interface/Sources/BottleArrivalFeatureInterface.swift
  Projects/Feature/BottleArrival/Interface/Sources/BottleArrivalView.swift
  Projects/Feature/BottleArrival/Project.swift
  Projects/Feature/BottleArrival/Sources/Source.swift
  Projects/Feature/BottleArrival/Testing/Sources/BottleArrivalTesting.swift
  Projects/Feature/BottleArrival/Tests/Sources/BottleArrivalTest.swift
  Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupFeature.swift
  Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupView.swift
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootView.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachView.swift
  Projects/Feature/Sources/App/AppFeature.swift
  Projects/Feature/Sources/TabView/MainTabView.swift
  Projects/Feature/Sources/TabView/MainTabViewFeature.swift
  graph.png
Labels: 💎 Feature

#114 [Feature/#106] navigationbar 커스텀
  Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupFeature.swift
  Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupView.swift
  Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadFeature.swift
  Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadView.swift
  Projects/Feature/SandBeach/Project.swift
  Projects/Shared/DesignSystem/Sources/Modifiers/NavigationBarModifier.swift
Labels: 💎 Feature

#120 [Feature/#109] LaunchScreen 및 앱 아이콘 적용
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120 1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40 1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40 2.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58 1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80 1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  Projects/App/Resources/Assets.xcassets/splashColor.colorset/Contents.json
  Projects/App/Resources/Assets.xcassets/splashImage.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/splashImage.imageset/icon_splash.svg
  Projects/Feature/Sources/App/AppView.swift
  Projects/Feature/Sources/SplashView/SplashView.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: ⚙️ Setting

#118 Feature/#105 핑퐁 상세 소개 탭 구현
  Projects/Domain/Auth/Interface/Sources/API/AuthAPI.swift
  Projects/Domain/Bottle/Interface/Sources/API/BottleAPI.swift
  Projects/Domain/Bottle/Interface/Sources/BottleClient.swift
  Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottlePingPongResponseDTO.swift
  Projects/Domain/Bottle/Interface/Sources/Entity/BottlePingPong.swift
  Projects/Domain/Bottle/Sources/BottleClient.swift
  Projects/Feature/BottleStorage/Example/Sources/AppView.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/PingPongTest/FinalSelectPingPongTestView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/PingPongTest/PhotoSharePingPongTestView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/PingPongTest/QuestionPingPongTestView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/Letter/LettetCardView.swift
  Projects/Shared/DesignSystem/Sources/Font/BottleFontSystem+WantedSans.swift
Labels: 💎 Feature

#123 [Feature/#112] 신고하기 화면 및 기능 구현
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Projects/Domain/Report/Interface/Sources/API/ReportAPI.swift
  Projects/Domain/Report/Interface/Sources/DTO/Request/ReportUserRequestDTO.swift
  Projects/Domain/Report/Interface/Sources/Entity/UserReportInfo.swift
  Projects/Domain/Report/Interface/Sources/ReportClient.swift
  Projects/Domain/Report/Project.swift
  Projects/Domain/Report/Sources/ReportClient.swift
  Projects/Domain/Report/Sources/Source.swift
  Projects/Domain/Report/Testing/Sources/ReportTesting.swift
  Projects/Domain/Report/Tests/Sources/ReportTest.swift
  Projects/Feature/Report/Example/Sources/AppView.swift
  Projects/Feature/Report/Interface/Sources/ReportUserFeature.swift
  Projects/Feature/Report/Interface/Sources/ReportUserFeatureInterface.swift
  Projects/Feature/Report/Interface/Sources/ReportUserView.swift
  Projects/Feature/Report/Interface/Sources/UserReportProfile.swift
  Projects/Feature/Report/Project.swift
  Projects/Feature/Report/Sources/Source.swift
  Projects/Feature/Report/Testing/Sources/ReportTesting.swift
  Projects/Feature/Report/Tests/Sources/ReportTest.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/UserProfile/UserProfileView.swift
  Projects/Shared/DesignSystem/Sources/Components/TextField/LineTextField/LineTextField.swift
  Projects/Shared/DesignSystem/Sources/Modifiers/EndEditingModifier.swift
Labels: 💎 Feature

#126 [Feature/#122] 보틀 보관함 가치관 문답 탭 구현
  Projects/Domain/Bottle/Interface/Sources/API/BottleAPI.swift
  Projects/Domain/Bottle/Interface/Sources/BottleClient.swift
  Projects/Domain/Bottle/Interface/Sources/DTO/Request/BottleImageShareRequestDTO.swift
  Projects/Domain/Bottle/Interface/Sources/DTO/Request/FinalSelectRequestDTO.swift
  Projects/Domain/Bottle/Interface/Sources/DTO/Request/RegisterLetterAnswerRequestDTO.swift
  Projects/Domain/Bottle/Sources/BottleClient.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/QuestionPingPongView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
  Projects/Feature/Sources/App/AppFeature.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/Stop/StopCardView.swift
Labels: 💎 Feature

#128 [feature/#116] 일반 회원 가입 약관 연결 웹뷰 이벤트 핸들링 추가
  Projects/Core/WebView/Interface/Sources/BottleWebViewAction.swift
  Projects/Domain/WebView/Sources/WebViewClient.swift
  Projects/Feature/GeneralSignUp/Interface/Sources/GeneralSignUpFeature.swift
  Projects/Feature/GeneralSignUp/Interface/Sources/GeneralSignUpFeatureInterface.swift
  Projects/Feature/GeneralSignUp/Interface/Sources/GeneralSignUpView.swift
  Projects/Feature/GeneralSignUp/Interface/Sources/TermsWebView.swift
Labels: 💎 Feature

#130 [feature/#127] BottleStorage ReportFeature 연결
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift
  Projects/Feature/Report/Interface/Sources/ReportUserFeature.swift
  Projects/Feature/Report/Interface/Sources/ReportUserFeatureInterface.swift
Labels: 💎 Feature

#132 [feature#111] 이미지 다운샘플링 구현
  Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadView.swift
  Projects/Shared/DesignSystem/Sources/Extension/UIImage+Extensions.swift
Labels: 💎 Feature

#136 [feature#134] 프로필 이미지 비율 수정
  Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadView.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon/icon_clearDelete.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon/icon_plus.imageset/Contents.json
  Projects/Shared/DesignSystem/Sources/Components/ETC/ImagePickerButton.swift
  Projects/Shared/DesignSystem/Sources/Components/ImageView/RemoteImageView.swift
Labels: 💎 Feature

#137 [feature/#135] 로그인 시 프로필 등록여부 확인 로직 수정
  Projects/Domain/Auth/Interface/Sources/DTO/Response/SignInResponseDTO.swift
Labels: 🐞 Bug

#140 [Feature/#139] TabBar Modifier 구현 및 적용
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift
  Projects/Feature/BottleStorage/Project.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Feature/MyPage/Project.swift
  Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupView.swift
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootView.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift
  Projects/Feature/SandBeach/Project.swift
  Projects/Feature/Sources/TabView/MainTabView.swift
  Projects/Feature/Sources/TabView/MainTabViewFeature.swift
  Projects/Feature/Sources/TabView/TabType.swift
  Projects/Feature/TabBar/Example/Sources/AppView.swift
  Projects/Feature/TabBar/Interface/Sources/TabBarModifier.swift
  Projects/Feature/TabBar/Interface/Sources/TabType.swift
  Projects/Feature/TabBar/Project.swift
  Projects/Feature/TabBar/Sources/Source.swift
  Projects/Feature/TabBar/Testing/Sources/TabBarTesting.swift
  Projects/Feature/TabBar/Tests/Sources/TabBarTest.swift
Labels: 💎 Feature

#142 [Feature/#138] 모래사장화면 새로운 보틀 도착 시간표시 구현
  Projects/Domain/Bottle/Interface/Sources/BottleClient.swift
  Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottleListResponseDTO.swift
  Projects/Domain/Bottle/Interface/Sources/Entity/UserBottleInfo.swift
  Projects/Domain/Bottle/Sources/BottleClient.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/UserStateType.swift
  Projects/Shared/Util/Interface/Sources/Date+Extensions.swift
Labels: 💎 Feature

#147 [Feature/#145] 자기소개 작성 후 마이페이지 유저 데이터 업데이트 구현
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift
  Projects/Feature/Sources/TabView/MainTabViewFeature.swift
  Projects/Feature/TabBar/Interface/Sources/TabBarModifier.swift
Labels: 🛠️ Refactor

#146 [Feature/#141] 보틀 가치관 문답 상태관리 개선
  Projects/Domain/Bottle/Interface/Sources/DTO/Request/FinalSelectRequestDTO.swift
  Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottlePingPongResponseDTO.swift
  Projects/Domain/Bottle/Interface/Sources/Entity/BottlePingPong.swift
  Projects/Domain/Bottle/Sources/BottleClient.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/FinalSelectPingPongView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PhotoSharePingPongView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift
Labels: 💎 Feature

#149 [Feature/#148] UITabBarController TabBar hidden 처리
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift
  Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupView.swift
  Projects/Feature/Sources/TabView/MainTabView.swift
Labels: 🐞 Bug, 💎 Feature

#154 [feature/#151] 매칭화면 장소 추천 기능 추가
  Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottlePingPongResponseDTO.swift
  Projects/Domain/Bottle/Interface/Sources/Entity/BottlePingPong.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: 💎 Feature

#161 [Feature/#153] 프로필 설정 중 앱 종료 시 대응
  Projects/Domain/Profile/Interface/Sources/API/ProfileAPI.swift
  Projects/Domain/Profile/Interface/Sources/DTO/Response/ProfileStatusResponseDTO.swift
  Projects/Domain/Profile/Interface/Sources/Entity/UserProfileStatus.swift
  Projects/Domain/Profile/Interface/Sources/ProfileClient.swift
  Projects/Domain/Profile/Sources/ProfileClient.swift
  Projects/Feature/Sources/App/AppFeature.swift
  Projects/Feature/Sources/App/AppView.swift
Labels: 🐞 Bug, 💎 Feature

#157 [Feature/#156] blur profile image view 구현
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/UserProfile/UserProfileView.swift
  Projects/Shared/DesignSystem/Sources/Components/ImageView/BlurImageView.swift
  Projects/Shared/DesignSystem/Sources/Components/ListItem/BottleStorageItem.swift
Labels: 💎 Feature

#164 [Feature/#162] 일반 로그인 변경된 UI 적용
  Projects/Feature/Login/Interface/Sources/Login/LoginFeature.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeatureInterface.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButton.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButtonStyle.swift
  graph.png
Labels: 💎 Feature

#170 [Feature/#165] 애플 로그인 구현
  Projects/App/Bottle.entitlements
  Projects/App/Project.swift
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/Core/KeyChainStore/Interface/Sources/TokenStoreProperties.swift
  Projects/Core/Network/Interface/Sources/API/AnyAPIType.swift
  Projects/Core/Network/Sources/Interceptor/TokenInterceptor.swift
  Projects/Domain/Auth/Interface/Sources/API/AppleAuthAPI.swift
  Projects/Domain/Auth/Interface/Sources/API/AuthAPI.swift
  Projects/Domain/Auth/Interface/Sources/AuthClient.swift
  Projects/Domain/Auth/Interface/Sources/DTO/Response/AppleTokenResponseDTO.swift
  Projects/Domain/Auth/Interface/Sources/DTO/Response/ClientSecretResponseDTO.swift
  Projects/Domain/Auth/Interface/Sources/LoginManager/LoginManager.swift
  Projects/Domain/Auth/Sources/AuthClient.swift
  Projects/Domain/Auth/Sources/LoginManager/AppleLoginManager.swift
  Projects/Domain/Auth/Sources/LoginManager/LoginManager.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeature.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeatureInterface.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/Sources/App/AppFeature.swift
  Projects/Feature/Sources/App/SceneDelegateFeature.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon/icon_appleLogo.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/icon/icon_appleLogo.imageset/icon_appleLogo.svg
  Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButton.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButtonStyle.swift
  Projects/Shared/DesignSystem/Sources/Image/BottleImageSystem+Icon.swift
Labels: 💎 Feature

#169 [feature/167] 자기소개 등록 indicator 추가
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift
  Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootView.swift
Labels: 💎 Feature

#171 [Feature/#166] firebase 초기 설정 및 fcm 연결
  .gitignore
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/TargetDependency+SPM.swift
  Projects/App/Bottle.entitlements
  Projects/App/Sources/AppDelegate.swift
  Projects/Domain/Auth/Interface/Sources/API/AuthAPI.swift
  Projects/Domain/Auth/Interface/Sources/AuthClient.swift
  Projects/Domain/Auth/Interface/Sources/DTO/Request/LogOutRequestDTO.swift
  Projects/Domain/Auth/Interface/Sources/DTO/Request/SignInRequestDTO.swift
  Projects/Domain/Auth/Sources/AuthClient.swift
  Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupView.swift
  Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadView.swift
  Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift
  Projects/Feature/Sources/SplashView/SplashView.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/image/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/image_splash.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/image_splash.imageset/icon_splash.svg
  Projects/Shared/DesignSystem/Sources/Image/BottleImageSystem+Illustraition.swift
  Projects/Shared/ThirdPartyLib/Project.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
  Tuist/ProjectDescriptionHelpers/Settings+Templates.swift
Labels: 💎 Feature

#173 Feature/#165 애플 로그인 추가 구현
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/Domain/Auth/Interface/Sources/API/AuthAPI.swift
  Projects/Domain/Auth/Interface/Sources/AuthClient.swift
  Projects/Domain/Auth/Interface/Sources/DTO/Request/ProfileRequestDTO.swift
  Projects/Domain/Auth/Interface/Sources/DTO/Response/SignInResponseDTO.swift
  Projects/Domain/Auth/Interface/Sources/Entity/SignInResult.swift
  Projects/Domain/Auth/Interface/Sources/LoginManager/LoginManager.swift
  Projects/Domain/Auth/Sources/AuthClient.swift
  Projects/Domain/Auth/Sources/LoginManager/AppleLoginManager.swift
  Projects/Domain/Auth/Sources/LoginManager/LoginManager.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeature.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeatureInterface.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
  Projects/Feature/Sources/App/AppFeature.swift
  Projects/Feature/Sources/App/AppView.swift
  Projects/Feature/Sources/App/SceneDelegateFeature.swift
  Projects/Feature/Sources/TabView/MainTabView.swift
  Projects/Feature/Sources/TabView/MainTabViewFeature.swift
  Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: 💎 Feature

#175 [Feature/#155] UserClient 구현
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift
  Projects/Domain/Auth/Interface/Sources/AuthClient.swift
  Projects/Domain/Auth/Sources/AuthClient.swift
  Projects/Domain/Auth/Sources/DataSource/LocalAuthDataSourceImpl.swift
  Projects/Domain/User/Interface/Sources/UserClient.swift
  Projects/Domain/User/Project.swift
  Projects/Domain/User/Sources/UserClient.swift
  Projects/Domain/User/Testing/Sources/UserTesting.swift
  Projects/Domain/User/Tests/Sources/UserTest.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeature.swift
  Projects/Feature/Sources/App/AppFeature.swift
Labels: 💎 Feature

#177 [Feature/#176] 유효하지 않은 토큰으로 로그인 시 에러 처리
  Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
  Projects/Feature/Sources/App/AppFeature.swift
Labels: 🐞 Bug

#189 [Feature/#185] 핑퐁 캡쳐 방지 기능 추가
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PhotoSharePingPongView.swift
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Resources/Images.xcassets/image/image_splash.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Images.xcassets/image/image_splash.imageset/icon_splash.svg
  Projects/Shared/DesignSystem/Sources/Components/ImageView/RemoteImageView.swift
  Projects/Shared/DesignSystem/Sources/ScreenShotPrevent/ScreenShotPreventView.swift
Labels: 💎 Feature

#186 [Feature/#147] 프로필 이미지 blur 처리 적용
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift
  Projects/Feature/Report/Interface/Sources/ReportUserView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/UserProfileTest/UserProfileTestView.swift
  Projects/Shared/DesignSystem/Sources/Components/Card/UserProfile/UserProfileView.swift
Labels: 💎 Feature

#191 [Feature/#187] 이미지 선택시 PhotosPickerItem 삭제
  Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadView.swift
Labels: 🐞 Bug

#190 [Feature/#188] 핑퐁 조회 API 연결
  Projects/Domain/Bottle/Interface/Sources/API/BottleAPI.swift
  Projects/Domain/Bottle/Interface/Sources/BottleClient.swift
  Projects/Domain/Bottle/Interface/Sources/Entity/BottleStorageList.swift
  Projects/Domain/Bottle/Sources/BottleClient.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift
Labels: 💎 Feature

#196 [Feature/#194] 애플 로그인 sns 버튼 클릭시 보이도록 수정
  Projects/Feature/Login/Interface/Sources/Login/AppleLoginFeature.swift
  Projects/Feature/Login/Interface/Sources/Login/AppleLoginFeatureInterface.swift
  Projects/Feature/Login/Interface/Sources/Login/AppleLoginView.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeature.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginFeatureInterface.swift
  Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
Labels: 💎 Feature

#202 [Feature/#199] 핑퐁 문답 화면 pull to refresh 구현
  Projects/Feature/BottleStorage/Example/Sources/AppView.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeatureInterface.swift
  Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift
Labels: 💎 Feature

#205 [Feature/#204] 카카오로그인 충돌
  Projects/App/Sources/AppDelegate.swift
  Projects/Domain/Auth/Sources/AuthClient.swift
  Projects/Domain/User/Interface/Sources/UserClient.swift
  Projects/Domain/User/Sources/UserClient.swift
  Projects/Feature/Sources/App/AppDelegateFeature.swift
  Projects/Feature/Sources/App/AppFeature.swift
Labels: 🐞 Bug

#221 [Feature#220] 이미지 다운 샘플링 reszieScale 수정
  Projects/Shared/DesignSystem/Sources/Extension/UIImage+Extensions.swift
Labels: 🐞 Bug
