Repository Nexters/Bottles_iOS, pull requests merged in 2024-07, with the labels that each got.

#8 [Setting/#7] tuist makefile 명령어 수정 및 추가
  Makefile
Labels: ⚙️ Setting

#29 [Feature/#28] 버튼 생성 모디파이어들 추가
  Projects/Core/Util/Sources/Modifiers/AsButtonModifier.swift
  Projects/Core/Util/Sources/Modifiers/AsDebounceButtonModifier.swift
  Projects/Core/Util/Sources/Modifiers/AsThrottleButtonModifier.swift
Labels: ⚙️ Setting

#31 [Setting/#30] uiuserinterfacestyle,UI supported interface orientations 세팅
  Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
Labels: ⚙️ Setting

#32 [Setting/#3] TabType 코드 파일 생성해 분리
  Projects/Feature/Sources/TabView/MainTabView.swift
  Projects/Feature/Sources/TabView/TabType.swift
Labels: 🛠️ Refactor, ⚙️ Setting

#34 [feature#14] SwfitUI import 누락 수정
  Projects/Shared/DesignSystem/Sources/Token/ColorToken+Background.swift
  Projects/Shared/DesignSystem/Sources/Token/ColorToken+Border.swift
Labels: 💎 Feature

#35 [Feature/#22] Spacing DesignSystem 구현
  Projects/Shared/DesignSystem/Sources/Spacing/HStack+Spacing.swift
  Projects/Shared/DesignSystem/Sources/Spacing/Spacable.swift
  Projects/Shared/DesignSystem/Sources/Spacing/Spacer+Extensions.swift
  Projects/Shared/DesignSystem/Sources/Spacing/VStack+Spacing.swift
Labels: 💎 Feature

#39 [Feature/#36] Padding DesignSystem 구현
  Projects/Shared/DesignSystem/Sources/Padding/BottlePaddingType.swift
  Projects/Shared/DesignSystem/Sources/Padding/View+Padding.swift
Labels: 💎 Feature

#41 [feature/#37] Radius DesignSystem 구현
  Projects/Shared/DesignSystem/Sources/Radius/BottleRadiusType.swift
Labels: 💎 Feature

#40 [Feature/#33] Custom Font Text View 구현
  Projects/Shared/DesignSystem/Example/Sources/AppView.swift
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/LaundaryGothicsStyleTextTestView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/RobotoStyleTextTestView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/TestView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/WantedSansStyleTextTestView.swift
  Projects/Shared/DesignSystem/Resources/Font/LaundryGothic/LaundryGothicOTF-Bold.otf
  Projects/Shared/DesignSystem/Resources/Font/LaundryGothic/LaundryGothicOTF-Regular.otf
  Projects/Shared/DesignSystem/Sources/Font/BottleFontSystem+LaundryGothic.swift
  Projects/Shared/DesignSystem/Sources/Font/BottleFontSystem+Rotobo.swift
  Projects/Shared/DesignSystem/Sources/Font/BottleFontSystem+WantedSans.swift
  Projects/Shared/DesignSystem/Sources/Source.swift
  Projects/Shared/DesignSystem/Sources/Text/CustomStyleText.swift
  Projects/Shared/DesignSystem/Sources/Text/LaundryGothicStyleText.swift
  Projects/Shared/DesignSystem/Sources/Text/RobotoStyleText.swift
  Projects/Shared/DesignSystem/Sources/Text/WantedSansStyleText.swift
  Projects/Shared/DesignSystem/Sources/Token/ColorToken+TextToken.swift
Labels: 💎 Feature

#45 [Feature/#42] Solid Button DesignSystem 구현
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/SolidButtonTest/SolidButtonTestView.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButton.swift
  Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButtonStyle.swift
  Projects/Shared/DesignSystemThirdPartyLib/Project.swift
  Projects/Shared/Project.swift
  Projects/Shared/ThirdPartyLib/Project.swift
  graph.png
Labels: 💎 Feature

#47 [Feature/#17] LinesTextField DesignSystem 구현
  Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/LinesTextFieldTest/IntroductionTextFieldTestView.swift
  Projects/Shared/DesignSystem/Example/Sources/SubViews/LinesTextFieldTest/LetterTextFieldTestView.swift
  Projects/Shared/DesignSystem/Sources/Components/TextField/LinesTextField/LinesTextField.swift
  Projects/Shared/DesignSystem/Sources/Components/TextField/LinesTextField/TextFieldState.swift
  Projects/Shared/DesignSystem/Sources/Extension/Text+Color.swift
  Projects/Shared/DesignSystem/Sources/Extension/Text+Font.swift
  Projects/Shared/DesignSystem/Sources/Extension/View+Extensions.swift
  Projects/Shared/DesignSystem/Sources/Text/CustomStyleText.swift
Labels: 💎 Feature
